/* Function prototypes */
void DisplayUsage( void );
void Initialize( GlgObject );
void SetCreateMode( void );
void TraceCB( GlgObject, GlgAnyType, GlgAnyType );
void InputCB( GlgObject, GlgAnyType, GlgAnyType );
void SelectGlgObject( GlgObject, ObjectType );
GlgObject AddNodeAt( long, GlgPoint* );
GlgObject NewNodeCopy( GlgObject );
GlgObject AddLinkObject( long );
void ConstrainLinkPoint( GlgObject, GlgObject, long );
void SetArcMiddlePoint( GlgObject link );
void AttachFramePoints( GlgObject link );
void SetLastPoint( GlgObject, GlgPoint*, GlgBoolean );
void AddLinkPoint( GlgObject, long );
void SetEdgeDirection( GlgObject, GlgPoint*, GlgPoint* );
void SetRectPoints( GlgObject, GlgPoint*, GlgPoint* );
GlgObject GetSelectedObject( GlgObject, ObjectType* );
void ResetModes( void );
long FinishLink( GlgObject link );
void SetPrompt( char* );
void SetError( char* );
void SetObjectName( GlgObject, char*, long );
void SetObject( GlgObject*, GlgObject );
void SetString( char**, char* );
long NoSelection( void );
void AddNode( char*, GlgObject );
void AddLink( char*, GlgObject );
void Cut( void );
void Paste( void );
void Save( void );
void Load( void );
void Quit( void );
void Print( void );
void ChangeZoom( double );
void ResetZoom( double );
long ApplyData( void );
void FillData( void );
void ZoomTo( void );
void SetDefaultName( GlgObject );
void SetRadioBox( char* );
GlgObject GetCPContainer( GlgObject, long* );
void AddNodeHandler( EventType, GlgPoint* );
void ZoomToHandler( EventType, GlgPoint* );
void AddLinkHandler( EventType, GlgPoint*, GlgObject, 
			      GlgTraceCBStruct* );
void ShowAttachmentPoints( GlgObject, GlgObject, GlgObject, long );
long EraseAttachmentPoints( void );
void ObjectHandler( EventType, GlgPoint*, GlgObject, 
			      GlgTraceCBStruct* );
void DraggingHandler( EventType, GlgPoint* );
void MoveLink( GlgObject link, GlgPoint* start_point,
			GlgPoint* end_point );
GlgObject GetObjectsAtCursor( GlgObject, GlgObject, GlgPoint* );
GlgObject GetAttachmentPoints( GlgObject, char* );
GlgObject GetSelectedPoint( GlgObject, GlgPoint* );
void PlaceObject( GlgObject, GlgPoint* );
void FillObjectPalette( char*, char*, long );
long FillObjectPaletteFromArray( GlgObject, char*, long, GlgObject, 
                                          GlgObject, char* );
void SetupObjectPalette( char* button_name, long start_index );
void GetPaletteIcons( GlgObject, char*, GlgObject, GlgObject );
double GetIconZoomFactor( GlgObject, GlgObject );
void FinalizeLink( GlgObject );
GlgObject CreateNode( long );
GlgObject CreateLink( long );
void AddLinkPoints( GlgObject, long );
char * GetObjectLabel( GlgObject, ObjectType );
char * GetObjectData( GlgObject, ObjectType );
char * GetObjectDataSource( GlgObject, ObjectType );
void SetObjectLabel( GlgObject, ObjectType, char* );
void SetObjectData( GlgObject, ObjectType, char* );
void SetObjectDataSource( GlgObject, ObjectType, char* );
void AddCustomData( GlgObject object, char * name, char * value );
void AddObjectCB( GlgObject, long );
void SelectObjectCB( GlgObject, long );
void CutObjectCB( GlgObject, long );
void PasteObjectCB( GlgObject, long );
void UpdateProcessDiagram( GlgAnyType, GlgLong* );
double GetTagValue( char*, GlgObject );
