GlgObject ReadPalette( char * palette_file );
GlgObject ReadFacilities( char * facilities_filename );
GlgObject ConnectFacilities( char * links_filename );
void GetExtentInfo( GlgObject info_obj );
void Input( GlgObject viewport, GlgAnyType client_data, GlgAnyType call_data );
void Trace( GlgObject viewport, GlgAnyType client_data, GlgAnyType call_data );
char * CreateLocationString( double world_x, double world_y );
void StartUpdate( GlgObject map_drawing );
void UpdateMap( GlgAnyType client_data, GlgLong* );
void ToggleResource( GlgObject object, char * res_name );
void Highlight( GlgObject drawing, GlgObject sel_object );
void LoadMap( void );
void UnloadMap( void );
void SetIconSize( void );
GlgObject AddNode( GlgObject, char*, double, double );
GlgObject AddLink( GlgObject, int, int, char* );
void GetXY( GlgPoint*, GlgPoint* );
void GetLatLon( GlgPoint*, GlgPoint* );
void error( char*, GlgBoolean );
